In [6]:
import numpy as np

# ===== TRANSITION MATRIX =====
P = np.array([[0.6,  0.3,  0.1 ],
              [0.25, 0.5,  0.25],
              [0.15, 0.35, 0.5 ]])

print("Transition Matrix P:")
print(P)

# ===== PART (i) - TWO STEP MATRIX =====
P_2 = np.dot(P, P)
print("\nTwo-step Transition Matrix P²:")
print(np.round(P_2, 4))

# ===== PART (ii) - STARTING FROM LOW TRAFFIC =====
Pi = np.array([1, 0, 0])

P_4 = np.dot(P_2, P_2)
P_5 = np.dot(P, P_4)

Pi_1 = np.dot(Pi, P)
Pi_2 = np.dot(Pi, P_2)
Pi_5 = np.dot(Pi, P_5)

print("\nStarting from Low Traffic (S1):")
print("After 1 hour :", np.round(Pi_1, 4))
print("After 2 hours:", np.round(Pi_2, 4))
print("After 5 hours:", np.round(Pi_5, 4))

# ===== PART (iii) METHOD 1 - LINEAR EQUATIONS =====
print("\n--- Steady State: Linear Equations Method ---")

PT = P.T
A = PT - np.eye(3)
A[2] = [1, 1, 1]
b = np.array([0, 0, 1])
pi_linear = np.linalg.solve(A, b)

print("Steady-state probability vector (π):")
print(np.round(pi_linear, 4))
print("Sum of probabilities:", round(sum(pi_linear), 4))

# ===== PART (iii) METHOD 2 - EIGENVECTOR METHOD =====
print("\n--- Steady State: Eigenvector Method ---")

eigenvalues, eigenvectors = np.linalg.eig(PT)
print("Eigenvalues :", np.round(eigenvalues, 4))
print("Eigenvectors:\n", np.round(eigenvectors, 4))

index = np.argmin(np.abs(eigenvalues - 1))
steady_state = eigenvectors[:, index]
steady_state = steady_state / np.sum(steady_state)
steady_state = steady_state.real

print("\nSteady-state probability vector (π):")
print(np.round(steady_state, 4))
print("Sum of probabilities:", round(sum(steady_state), 4))

# ===== VERIFICATION =====
print("\n--- Verification: π × P should equal π ---")
print("π × P =", np.round(np.dot(pi_linear, P), 4))
print("π     =", np.round(pi_linear, 4))

# ===== PART (iv) - INTERPRETATION =====
print("""
--- Meaning of Stationary Distribution ---

Steady state π = [π1, π2, π3] means:

In the LONG RUN:
- π1 = % of hours airport is in LOW traffic
- π2 = % of hours airport is in MODERATE traffic
- π3 = % of hours airport is in HEAVY traffic

Starting state does NOT matter in the long run.
These probabilities remain fixed over time.
""")

Transition Matrix P:
[[0.6  0.3  0.1 ]
 [0.25 0.5  0.25]
 [0.15 0.35 0.5 ]]

Two-step Transition Matrix P²:
[[0.45   0.365  0.185 ]
 [0.3125 0.4125 0.275 ]
 [0.2525 0.395  0.3525]]

Starting from Low Traffic (S1):
After 1 hour : [0.6 0.3 0.1]
After 2 hours: [0.45  0.365 0.185]
After 5 hours: [0.3523 0.39   0.2577]

--- Steady State: Linear Equations Method ---
Steady-state probability vector (π):
[0.3439 0.3915 0.2646]
Sum of probabilities: 1.0

--- Steady State: Eigenvector Method ---
Eigenvalues : [1.     0.4323 0.1677]
Eigenvectors:
 [[-0.5885 -0.7651  0.2852]
 [-0.6699  0.1355 -0.8052]
 [-0.4527  0.6295  0.5199]]

Steady-state probability vector (π):
[0.3439 0.3915 0.2646]
Sum of probabilities: 1.0

--- Verification: π × P should equal π ---
π × P = [0.3439 0.3915 0.2646]
π     = [0.3439 0.3915 0.2646]

--- Meaning of Stationary Distribution ---

Steady state π = [π1, π2, π3] means:

In the LONG RUN:
- π1 = % of hours airport is in LOW traffic
- π2 = % of hours airport is in MODERA