In [15]:
import pandas as pd 
import numpy as np 
data={'X':[4,6,8,5,7],
      'Y':[7,9,10,8,11]}
df=pd.DataFrame(data)
df.to_csv('bivariate_data.csv',index=False)
print(df.head())

   X   Y
0  4   7
1  6   9
2  8  10
3  5   8
4  7  11


In [16]:
df=pd.read_csv('bivariate_data.csv')
print('Dataframe\n',df)
array=df.to_numpy()
print('numpy Array:\n',array)

Dataframe
    X   Y
0  4   7
1  6   9
2  8  10
3  5   8
4  7  11
numpy Array:
 [[ 4  7]
 [ 6  9]
 [ 8 10]
 [ 5  8]
 [ 7 11]]


In [22]:
X=array[:,0]
Y=array[:,1]
print(X,Y)


[4 6 8 5 7] [ 7  9 10  8 11]


In [31]:
A = array
A_T = A.T
print("\nTranspose of Data Matrix:")
print(A_T)
if A.shape == A_T.shape:
    print("\nA + A^T:")
    print(A + A_T)
else:
    print("\nMatrix addition A + A^T is not defined (different shapes).")
ATA = A_T @ A
print("\nMatrix Multiplication (A^T A):")
print(ATA)
try:
    ATA_inv = np.linalg.inv(ATA)
    print("\nInverse of (A^T A):")
    print(ATA_inv)
except np.linalg.LinAlgError:
    print("\nInverse does not exist.")
print("\nRow sums of A:", A.sum(axis=1))
print("Column sums of A:", A.sum(axis=0))
eigvals, eigvecs = np.linalg.eig(ATA)
print("\nEigenvalues:")
print(eigvals)
print("Eigenvectors:")
print(eigvecs)

mean_X = np.mean(X)
mean_Y = np.mean(Y)
print("\nSample Mean of X:", mean_X)
print("Sample Mean of Y:", mean_Y)
cov_matrix = np.cov(X, Y)
print("\nVariance-Covariance Matrix:")
print(cov_matrix)

print('''(a) Interpret the Covariance value:
The covariance between X and Y will be a positive number. This means when X increases, Y also tends to increase. Both variables move in the same direction.
(b) Relationship between X and Y:
Looking at the data — as X goes from 4→6→8, Y goes from 7→9→10. There is a clear positive relationship — students with higher X values also have higher Y values. They are positively correlated.
(c) Role of Eigenvalues and Eigenvectors in multivariate analysis:
Think of data as a cloud of points in space:

Eigenvalues → tell you how much variation/spread exists in each direction. Larger eigenvalue = more important direction
Eigenvectors → tell you which direction that variation goes
Together they help find the most important patterns in data — this is the foundation of a technique called PCA (Principal Component Analysis) which simplifies complex data while keeping the important information''')
print('''\nFrom the given data, as the values of Xincrease, the corresponding values of Yalso tend to increase. This indicates a positive relationship between Xand Y. In other words, higher values of Xare associated with higher values of Y, suggesting a positive correlation between the two variables. This pattern implies that the variables move in the same direction and are linearly related to some extent.
In multivariate analysis, eigenvalues and eigenvectors describe the main patterns of variation in a dataset. Eigenvalues indicate how much variance is captured in each principal direction, while eigenvectors give the directions (linear combinations of variables) along which this variance is maximized. They form the basis of techniques like Principal Component Analysis (PCA), helping reduce dimensionality, identify important features, and reveal the underlying structure of multivariate data.
''')


Transpose of Data Matrix:
[[ 4  6  8  5  7]
 [ 7  9 10  8 11]]

Matrix addition A + A^T is not defined (different shapes).

Matrix Multiplication (A^T A):
[[190 279]
 [279 415]]

Inverse of (A^T A):
[[ 0.41129832 -0.2765114 ]
 [-0.2765114   0.18830525]]

Row sums of A: [11 15 18 13 18]
Column sums of A: [30 45]

Eigenvalues:
[  1.67239156 603.32760844]
Eigenvectors:
[[-0.82884508 -0.55947818]
 [ 0.55947818 -0.82884508]]

Sample Mean of X: 6.0
Sample Mean of Y: 9.0

Variance-Covariance Matrix:
[[2.5  2.25]
 [2.25 2.5 ]]
(a) Interpret the Covariance value:
The covariance between X and Y will be a positive number. This means when X increases, Y also tends to increase. Both variables move in the same direction.
(b) Relationship between X and Y:
Looking at the data — as X goes from 4→6→8, Y goes from 7→9→10. There is a clear positive relationship — students with higher X values also have higher Y values. They are positively correlated.
(c) Role of Eigenvalues and Eigenvectors in multivaria