In [1]:
a=15
b=4
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

19
11
60
3.75
3
3
50625


In [2]:
x=[1,2,3,4,5]
y=[10,20,30,40,50]
print(x)
print(y)
print("Length of x:",len(x))
print("first element of x:",x[0])
print("last element of x:",x[-1])

[1, 2, 3, 4, 5]
[10, 20, 30, 40, 50]
Length of x: 5
first element of x: 1
last element of x: 5


In [3]:
#to replace the third element with the value 100
x[2]=100
print('updated x:',x)
z=x+y  #we do simply this for concatenation of two list i.e. adding of two lists
#Use when:you want to join (merge) two lists
#Don’t use when: You want element-wise operations
print(z)
del z[1]
print(z)
z.remove(40) #removes simply the values not index
print(z)
del y


updated x: [1, 2, 100, 4, 5]
[1, 2, 100, 4, 5, 10, 20, 30, 40, 50]
[1, 100, 4, 5, 10, 20, 30, 40, 50]
[1, 100, 4, 5, 10, 20, 30, 50]


In [4]:
x=[1,2,3,4,5]
y=[10,20,30,40,50]
result_loop=[]
for i in range(len(x)):
  result_loop.append(x[i]+y[i])
print(result_loop)

#for loop → When to use?👉 Use when:You want full control You need to: apply conditions use index do complex operations



#zip pairs elements from both lists
#zip(x, y) → (1,10), (2,20), (3,30), (4,40), (5,50)
#Use when:
#You just want simple element-wise operations. Lists are of same length
result_zip=[]
for a,b in zip(x,y):
  result_zip.append(a+b)
print(result_zip)

result=result_zip
print(result)

#For element-wise operations, zip() is preferred because it directly pairs elements of two lists and simplifies the code.
#A for loop is used when more control or conditions are required.
#The expression x + y performs concatenation, not element-wise addition, so it is not suitable.

[11, 22, 33, 44, 55]
[11, 22, 33, 44, 55]
[11, 22, 33, 44, 55]


In [5]:
five=[5,10,15,20,25]
print(sum(five))

75


In [6]:
data=[10,None,20,30,None,40]
missing_values= data.count(None)#counts the no. of elements in ()
print(missing_values)
cleaned=[x for x in data if x is not None]
#What’s happening here?
#This is called list comprehension (just a short way to write a loop)
#👉 It means:
#Go through each element x in data
#Keep it only if it is NOT None
print(cleaned)
print(sum(cleaned))

2
[10, 20, 30, 40]
100


In [7]:
L=[10,20,30,40]
T=(10,20,30,40)
L[1]=200
print('updated L:',L)

updated L: [10, 200, 30, 40]


In [12]:
try:
    T[1] = 200
except TypeError as e:
    print(f"Error: {e}")


#Think like this:

#try → “Let me try this risky thing”
#except → “If it fails, handle it calmly”
#When should you use this?
#Use try-except when:
#You expect possible errors
#You don’t want program to crash

#Examples:
#File handling
#User input
#Division (like divide by zero)
#Working with tuples like this
    
    
    #Why error?
#Because:
#👉 Tuple is immutable (cannot be changed)

Error: 'tuple' object does not support item assignment


In [10]:
#When to use what?
#✔ Use List when:
#Data changes frequently
#Example:
marks = [80, 85, 90]
marks[0] = 95
#✔ Use Tuple when:
#Data should stay fixed
#Example:
coordinates = (28.61, 77.23)
#👉 You don’t want location to change accidentally
print(marks,coordinates)

[95, 85, 90] (28.61, 77.23)


In [14]:
#List = Flexible
#Tuple = Fixed
#A list is preferred when the data needs to be modified, such as storing marks or items in a cart.
#A tuple is preferred when the data should remain fixed, such as coordinates or constant values.
#What is mutability?
#Mutability means:
#Can we change the data after creating it?
#The main difference between a list and a tuple is mutability.
#A list is mutable, meaning its elements can be changed after creation.
#A tuple is immutable, meaning its elements cannot be changed once it is created.


In [15]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([10,20,30,40,50])

print(x+y)
print(x-y)
print(x*y)
print(x/y)
#What happens here?
#👉 Unlike lists, NumPy automatically does element-wise operations
#Python lists do not support element-wise mathematical operations and require loops or zip().
#NumPy arrays support direct element-wise operations, making computations faster and easier.
#Therefore, NumPy arrays are preferred for numerical and scientific calculations.

print('NumPy arrays perform true element-wise operations directly with operators.',
'Python lists require manual iteration or list comprehension.',
'NumPy is much more efficient for numerical operations.',sep='\n')


[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
NumPy arrays perform true element-wise operations directly with operators.
Python lists require manual iteration or list comprehension.
NumPy is much more efficient for numerical operations.
